use std::time::{Duration, Instant};

use rquickjs::{Context, Runtime};
use serde::{Deserialize, Serialize};

use crate::runtime::contract::{FrameRenderResult, GrainContext, RuntimeDiagnostic};
use crate::runtime::raster::{DrawCommand, half_block_cells, render_commands};

const RUNNER_JS: &str = include_str!("js/runner.js");
const MAX_SOURCE_BYTES: usize = 256 * 1024;
const MAX_OUTPUT_BYTES: usize = 4 * 1024 * 1024;
const MAX_MEMORY_BYTES: usize = 32 * 1024 * 1024;
const MAX_STACK_BYTES: usize = 256 * 1024;
const MAX_CELLS: usize = 32_768;
const EVALUATION_BUDGET: Duration = Duration::from_millis(250);

#[derive(Serialize)]
struct RunnerRequest<'a> {
    source: &'a str,
    context: &'a GrainContext,
    #[serde(rename = "termCols")]
    term_cols: u16,
    #[serde(rename = "termRows")]
    term_rows: u16,
}

#[derive(Deserialize)]
struct RunnerResponse {
    success: bool,
    commands: Option<Vec<DrawCommand>>,
    width: Option<u32>,
    height: Option<u32>,
    error: Option<RuntimeDiagnostic>,
}

fn diagnostic(message: impl Into<String>) -> RuntimeDiagnostic {
    RuntimeDiagnostic {
        message: message.into(),
        line: None,
        column: None,
        stack: None,
    }
}

/// Evaluate in a fresh, capability-free JavaScript runtime. No host callbacks,
/// module loader, Node globals, process environment or I/O are exposed.
pub fn evaluate_frame(
    source: &str,
    context: &GrainContext,
    term_cols: u16,
    term_rows: u16,
) -> Result<FrameRenderResult, RuntimeDiagnostic> {
    if source.len() > MAX_SOURCE_BYTES {
        return Err(diagnostic("Sketch source exceeds the 256 KiB limit"));
    }
    if term_cols == 0
        || term_rows == 0
        || usize::from(term_cols) * usize::from(term_rows) > MAX_CELLS
        || context.width == 0
        || context.height == 0
        || context.width > 4096
        || context.height > 4096
    {
        return Err(diagnostic(
            "Invalid canvas dimensions or terminal cell limit exceeded",
        ));
    }
    if !context.time.is_finite()
        || ![
            context.audio.amplitude,
            context.audio.low,
            context.audio.mid,
            context.audio.high,
        ]
        .iter()
        .all(|value| value.is_finite())
    {
        return Err(diagnostic("Sketch context must contain finite numbers"));
    }

    let request = serde_json::to_string(&RunnerRequest {
        source,
        context,
        term_cols,
        term_rows,
    })
    .map_err(|error| diagnostic(format!("Cannot encode sketch request: {error}")))?;

    let runtime = Runtime::new()
        .map_err(|error| diagnostic(format!("Cannot initialize JavaScript runtime: {error}")))?;
    // Keep the default QuickJS allocator: a custom allocator would disable its
    // memory limit. The deadline covers compilation, drawing and serialization.
    runtime.set_memory_limit(MAX_MEMORY_BYTES);
    runtime.set_max_stack_size(MAX_STACK_BYTES);
    let deadline = Instant::now() + EVALUATION_BUDGET;
    runtime.set_interrupt_handler(Some(Box::new(move || Instant::now() >= deadline)));
    let js = Context::full(&runtime)
        .map_err(|error| diagnostic(format!("Cannot initialize sketch context: {error}")))?;
    let program = format!("(() => {{\n{RUNNER_JS}\nreturn run({request});\n}})()");
    // JS allocations, including the returned string, are bounded by the heap
    // budget. No exception getters or toString hooks are invoked from Rust.
    let output = js.with(|ctx| ctx.eval::<String, _>(program));
    if Instant::now() >= deadline {
        return Err(diagnostic(
            "Sketch execution exceeded its 250 ms time limit",
        ));
    }
    let output = output.map_err(|error| {
        diagnostic(format!(
            "Sketch execution failed (memory/stack limit or JavaScript exception): {error}"
        ))
    })?;
    if output.len() > MAX_OUTPUT_BYTES {
        return Err(diagnostic("Sketch output exceeds the 4 MiB limit"));
    }
    let response: RunnerResponse = serde_json::from_str(&output)
        .map_err(|error| diagnostic(format!("Invalid sketch output: {error}")))?;
    if !response.success {
        return Err(response
            .error
            .unwrap_or_else(|| diagnostic("Sketch evaluation failed")));
    }
    let commands = response
        .commands
        .ok_or_else(|| diagnostic("Sketch returned no drawing commands"))?;
    let raster = render_commands(
        response
            .width
            .ok_or_else(|| diagnostic("Sketch returned no canvas width"))?,
        response
            .height
            .ok_or_else(|| diagnostic("Sketch returned no canvas height"))?,
        &commands,
    )?;
    let cells = half_block_cells(&raster, term_cols, term_rows, 2.0, [0, 0, 0]);
    // Glyphs are generated by Rust, never copied from untrusted JavaScript.
    let ascii_art = cells
        .iter()
        .map(|row| {
            row.iter()
                .map(|cell| cell.symbol.as_str())
                .collect::<String>()
        })
        .collect::<Vec<_>>()
        .join("\n");
    Ok(FrameRenderResult {
        frame: context.frame,
        width: raster.width,
        height: raster.height,
        ascii_art: Some(ascii_art),
        cells: Some(cells),
        raster: Some(raster),
        draw_commands_count: commands.len(),
        revision: 0,
    })
}
