use std::path::PathBuf;

#[allow(dead_code)]
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Action {
    Quit,
    Tick,
    Resize(u16, u16),
    ToggleHelp,
    ToggleVersions,
    ToggleSelectModel,
    ToggleTuningModal,
    TuningNextParam,
    TuningPrevParam,
    TuningIncreaseParam,
    TuningDecreaseParam,
    TuningResetDefaults,
    SelectPreviousEngine,
    SelectNextEngine,
    ActivateSelectedEngine,
    SelectPreviousVersion,
    SelectNextVersion,
    RollbackToSelectedVersion,
    RollbackToVersion(usize),
    TogglePlayback,
    EnterPromptEdit,
    ExitPromptEdit,
    PromptInputChar(char),
    PromptBackspace,
    PromptDelete,
    PromptCursorLeft,
    PromptCursorRight,
    CommitPrompt,
    TriggerGenerate,
    GenerationCompleted {
        result: Result<String, String>,
        prompt: String,
    },
    EnterOpenAudio,
    ExitOpenAudio,
    AudioInputChar(char),
    AudioBackspace,
    CommitOpenAudio,
    LoadAudio(PathBuf),
    OpenInEditor,
    SetStatusMessage(String),
}
